package com.tj24.module_appmanager.greendao.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.tj24.module_appmanager.bean.AppBean;
import com.tj24.module_appmanager.bean.AppClassfication;

import com.tj24.module_appmanager.greendao.dao.AppBeanDao;
import com.tj24.module_appmanager.greendao.dao.AppClassficationDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig appBeanDaoConfig;
    private final DaoConfig appClassficationDaoConfig;

    private final AppBeanDao appBeanDao;
    private final AppClassficationDao appClassficationDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        appBeanDaoConfig = daoConfigMap.get(AppBeanDao.class).clone();
        appBeanDaoConfig.initIdentityScope(type);

        appClassficationDaoConfig = daoConfigMap.get(AppClassficationDao.class).clone();
        appClassficationDaoConfig.initIdentityScope(type);

        appBeanDao = new AppBeanDao(appBeanDaoConfig, this);
        appClassficationDao = new AppClassficationDao(appClassficationDaoConfig, this);

        registerDao(AppBean.class, appBeanDao);
        registerDao(AppClassfication.class, appClassficationDao);
    }
    
    public void clear() {
        appBeanDaoConfig.clearIdentityScope();
        appClassficationDaoConfig.clearIdentityScope();
    }

    public AppBeanDao getAppBeanDao() {
        return appBeanDao;
    }

    public AppClassficationDao getAppClassficationDao() {
        return appClassficationDao;
    }

}
